# Generated by Django 3.1.2 on 2024-10-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240922_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='actividades',
            field=models.ManyToManyField(blank=True, to='core.Actividad'),
        ),
    ]
