# Generated by Django 3.1.2 on 2024-10-17 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20241016_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadRealizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.TextField()),
                ('conducta', models.TextField()),
                ('consecuencia', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
