# Generated by Django 3.1.2 on 2024-10-18 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20241017_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareaasignada',
            old_name='paciente',
            new_name='asignada_a',
        ),
        migrations.RemoveField(
            model_name='tareaasignada',
            name='comentario_paciente',
        ),
        migrations.RemoveField(
            model_name='tareaasignada',
            name='completada',
        ),
        migrations.AddField(
            model_name='actividad',
            name='tareaasignada',
            field=models.ManyToManyField(blank=True, related_name='actividades_asignadas', to='core.TareaAsignada'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='imagen_url',
            field=models.CharField(default='default_image_url.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tareaasignada',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='core.actividad'),
        ),
        migrations.AlterField(
            model_name='tareaasignada',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
