# Generated by Django 3.1.2 on 2024-10-18 19:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20241018_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadrealizada',
            name='antecedentes',
            field=models.TextField(default='Sin antecedentes'),
        ),
        migrations.AddField(
            model_name='actividadrealizada',
            name='conducta',
            field=models.TextField(default='Sin conducta'),
        ),
        migrations.AddField(
            model_name='actividadrealizada',
            name='consecuencia',
            field=models.TextField(default='Sin consecuencia'),
        ),
        migrations.AddField(
            model_name='actividadrealizada',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 19, 50, 8, 545937, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuestatarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.tareaasignada'),
        ),
    ]
