# Generated by Django 3.1.2 on 2024-10-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20241018_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaasignada',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
