# Generated by Django 3.1.2 on 2024-10-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241016_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='paciente',
            new_name='es_paciente',
        ),
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='terapeuta',
            new_name='es_terapeuta',
        ),
    ]
