# Generated by Django 3.1.2 on 2024-10-18 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_actividadrealizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAsignada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('completada', models.BooleanField(default=False)),
                ('comentario_paciente', models.TextField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tareaasignada')),
            ],
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='tareas',
            field=models.ManyToManyField(blank=True, to='core.Tarea'),
        ),
    ]
