# Generated by Django 3.1.2 on 2024-10-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_actividad_tareaasignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tareas_asignadas',
            field=models.ManyToManyField(blank=True, related_name='actividades_asignadas', to='core.TareaAsignada'),
        ),
        migrations.AlterField(
            model_name='tareaasignada',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas_a_usuarios', to='core.actividad'),
        ),
    ]
