# Generated by Django 3.1.2 on 2024-10-22 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_initial_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('respuesta_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.respuestatarea')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
