# Generated by Django 3.1.2 on 2024-11-26 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_respuestatarea_fecha_realizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('actividad_realizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_actividad', to='core.actividadrealizada')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('respuesta_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tarea', to='core.respuestatarea')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
